### ISSUE TITLE
Please move this repo back to the spruce-net group

### ISSUE THREAD

**Issue by jgeurts** [jgeurts/spruce#8]
Hi Justin,

I'm doing a bit of work in .net again and would like the option to contribute to this library again. Can you please move this repository back to the [spruce-net organization](https://github.com/spruce-net)?

Thanks,

Jim

**Comment by jgeurts** [comment]
Hi @Ablecken, I wanted to bump this to see if you will have a chance to move the repo.

**Comment by Ablecken** [comment]
Heyo, will do, sorry for the delay

**Comment by Ablecken** [comment]
Done, no work was done on it while it was under my care.  I just didn't want it to vanish or become orphaned.

**Comment by jgeurts** [comment]
Thank you, sir!
